"""Dictionaries from Biologic."""
status_codes = {
    0: "Status",
    1: "Ox/Red",
    2: "OCV",
    3: "EIS",
    4: "Technique number",
    5: "Technique code",
    6: "Sequence number",
    7: "Current loop iteration number",
    8: "Current sequence within loop number",
    9: "Loop experiment iteration number",
    10: "Cycle number",
    11: "Counter 1",
    12: "Counter 2",
    13: "Counter 3",
    14: "Buffer size",
    15: "Time (s)",
    16: "Ewe (V)",
    17: "Ece (V)",
    18: "Eoc (V)",
    19: "I (A)",
    20: "Q-Q0 (Ah)",
    21: "Aux1",
    22: "Aux2",
    23: "Irange (A)",
    24: "R compensation (Ohm)",
    25: "Frequency (Hz)",
    26: "|Z| (Ohm)",
    27: "Current point index",
    28: "Total point index",
    29: "T (°C)",
    30: "Safety limit",
    31: "Connection",
}